[build]
  base = "/"
  publish = "./build"
  command = "npm run build:prod"

[dev]
  command = "npm run dev"
  targetPort = 3000
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200